#--------------------------------------------------------------
# Github Action Part-1 Basics
#
# Copyleft (c) by Mykhailo Kolodii
#

name: GitHubActions-Basics
  
on:
  push:
    branches:
      - master

jobs:
 my_test:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello Message in Test
      run : echo "Hello World from Teting job"  

 my_deploy:
    runs-on: ubuntu-latest 
    steps:
    - name: Print Hello Message in Deploy  
      run : echo "Hello World from deploy job"
