#--------------------------------------------------------------
# Github Action Part-1 Basics
#
# Copyleft (c) by Mykhailo Kolodii
#

name: GitHubActions-Basics
env:
  Aplications: "My_app"
  Package_name: "app_deploy-ver-${{ github.sha }}"
  
on:
  push:
    branches:
      - main

jobs:
 my_test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message in Test
      run : echo "Hello World from Teting job"  
      
    - name: Execute few commands
      run : |
        echo "Hello M1"
        echo "Hello M2"
        echo "App name: ${{ env.Aplications }}" 
        
    - name: List current 
      run : ls -la 
      
    - name: GitClone
      uses: actions/checkout@v1
        
    - name: List current 
      run : ls -la   
 
 my_deploy:
    runs-on: ubuntu-latest 
    needs: [my_test]
    
    steps:
    - name: Print Hello Message in Deploy  
      run : echo "Hello World from deploy job"
      
    - name: Print Deploy package
      run : echo "Deploy packcage name is ${{ env.Package_name }}"
